### ISSUE TITLE
Difference app and web directories?

### ISSUE THREAD

**Issue by oimos** [bshelling/craft-mac-n-cheez#1]
First of all, thank you for sharing this great set up pack for Craft CMS. It save my time!

I just have a quick question since I'm very new to Craft CMS actually.
After install Craft CMS with running the command, I see app directory but not sure what is it for. Is it for the dashboard?
I understand web directory is used for the first homepage.

**Comment by bshelling** [comment]
Hi @stoneshower, thanks for using it. The app folder is the project's directory and it's web directory is mapped to the directory in docker.
