### ISSUE TITLE
Error while accessing the install URL in Linux

### ISSUE THREAD

**Issue by asitemade4u** [bshelling/craft-mac-n-cheez#2]
Hi,
I am trying the script and face a warning then an error while accessing the install URL in the browser:

`Warning: require_once(/var/www/site/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/site/web/index.php on line 11
Fatal error: require_once(): Failed opening required '/var/www/site/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/site/web/index.php on line 11`

I checked the folder `/usr/local/lib/php ` within the container and there was no `autoload.php` file there.
Please help.
Best,
Stephen

**Comment by bshelling** [comment]
Hi Stephen,
My apologies for any errors you're experiencing. The error you're getting usually indicates you need to run a ```composer install``` command because the vendor folder doesn't exist. 
Are you experience during the default install or custom install?
